Repository trixi-framework/PointNeighbors.jl, pull requests merged in 2025-05, with the labels that each got.

#109 Add full support for parallelization backends
  Project.toml
  benchmarks/count_neighbors.jl
  benchmarks/n_body.jl
  benchmarks/plot.jl
  benchmarks/smoothed_particle_hydrodynamics.jl
  benchmarks/update.jl
  src/PointNeighbors.jl
  src/cell_lists/full_grid.jl
  src/gpu.jl
  src/neighborhood_search.jl
  src/nhs_grid.jl
  src/nhs_precomputed.jl
  src/nhs_trivial.jl
  src/util.jl
  test/cell_lists/full_grid.jl
  test/neighborhood_search.jl
  test/nhs_grid.jl
Labels: breaking changes

#110 Fix dispatch for bounds errors on GPU
  Project.toml
  src/cell_lists/full_grid.jl
Labels: bug, gpu

#101 Spatial Hashing
  Project.toml
  src/PointNeighbors.jl
  src/cell_lists/cell_lists.jl
  src/cell_lists/spatial_hashing.jl
  src/nhs_grid.jl
  test/cell_lists/spatial_hashing.jl
  test/neighborhood_search.jl
Labels: enhancement, gpu

#116 Make sure the type of `FullGridCellList` does not change with the search radius
  src/cell_lists/full_grid.jl
Labels: bug
